function [fitresult, gof] = GaussFit(d_hist, n_d)
%CREATEFIT(DX_HIST,N_DX)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : dx_hist
%      Y Output: n_dx
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 09-Jun-2014 19:36:09


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( d_hist, n_d );

% Set up fittype and options.
ft = fittype( 'gauss1' );
opts = fitoptions( ft );
opts.Display = 'Off';
opts.Lower = [-Inf -Inf 0];
opts.StartPoint = [max(n_d) 0 std(n_d)];
opts.Upper = [Inf Inf Inf];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure('color','white', 'name', 'Gaussian fit' );
h = plot( fitresult, xData, yData );
legend( h, 'dx histogram', 'Gaussian fit', 'Location', 'NorthEast' );
% Label axes
xlabel('dx (nm)');
ylabel('Occurences');
grid on
title(['x0 = ',num2str(fitresult.b1),' nm - Std = ',num2str(fitresult.c1),' nm'])


